db:
    image: mysql:5.7
    ports:
        - "127.0.0.1:3307:3306"
    environment:
        - "MYSQL_ROOT_PASSWORD=root"
        - "MYSQL_RANDOM_ROOT_PASSWORD=no"
        - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
        - "MYSQL_DATABASE=symfony"
        - "MYSQL_PASSWORD=root"

engine:
    build: ./docker/engine/
    volumes:
        - ".:/home/remi/site-remi:rw"
        - "./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
    links:
        - "db:db"
    working_dir: "/home/docker"

front:
    image: nginx
    ports:
        - "127.0.0.1:80:80"
    links:
        - "engine:engine"
    volumes:
        - ".:/home/remi/site-remi:ro"
        - "./docker/front/default.conf:/etc/nginx/conf.d/default.conf:ro"
